services:
  mysql:
    image: mysql:8.0
    container_name: fraud_mysql

    environment:
      MYSQL_DATABASE: fraud_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fraud_user
      MYSQL_PASSWORD: fraud_pass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mysql_data: